### ISSUE TITLE
Setup of the environment (OS wise)

### ISSUE THREAD

**Issue by almahdc** [almahdc/daido-project-onboarding#31]
- [x] Alma to prepare a document (guide) of crucial things 

[Daido app environment setup.docx](https://github.com/almahdc/daido-project-onboarding/files/4794619/Daido.app.environment.setup.docx)

- [ ] Tay to set up his environment running the app locally

**Comment by MaschinenTechno** [comment]
What I've done so far:
1. Create git repository from my Linux system
https://github.com/MaschinenTechno/DaidoTheOnboardAssistant
2. Got node.js and npm.
3. Read through npm documentation.
4. Installed and configure the Amplify CLI 
    Users with AWS Management Console access can sign-in at: https://684024349990.signin.aws.amazon.com/console

![Screenshot from 2020-06-22 13-49-34](https://user-images.githubusercontent.com/66864400/85284357-581f7100-b48f-11ea-93c0-d1f1c4ebd565.png)

5. Currently watching What Should you Know Before Learning Reactjs video
